// Desc: API Endpoints are stored in this file.
export default {
  Login: 'api/login',
  OtpVerify: 'api/verifyOtp',
  ResendOtp:'api/sendOtp',
  Home_Api: 'api/game/list',
  Profile: 'api/get_details',
  AdharOptSend: 'api/AadharVerificationSendOtp',
  AdharVerifyOtp: 'api/AadharVerificationVerifyOtp',
  Game_Ticket_List: 'api/ticket/getUserTicket',
  GameById :'/game/byId/',
  Store_Ticket: 'api/purchase_ticket/store',
  Game_Rule: 'api/getGameRules/list',
  Game_List: 'api/availableGame/list',
  LeaderBoardByGameId: 'api/game_score/byGameId',
  Global_ByDate: 'api/game_score/byDate',
  History_Api: 'api/game_score/getPlayedGamesByUserId',
  Game_History: 'api/game_score/by_user_id_and_game_id',
  Game_History_User : 'api/game_score/getScoreByParticularUserId',
  Contact: 'contactUs',
  Refund: 'refundPolicy',
  HowToPlay : "howToPlay",
  HelpSupport: 'helpAndSupport',
  Support :'support',
  TermCondition: 'termsAndCondition',
  Transaction_List: 'api/wallet/transactionList',
  Transaction_store: 'api/transaction/store',
  Bonus_wallet: 'api/bonus_wallet',
  checkPaymentStatus: 'api/checkPaymentStatus',
  DepositeTransaction: 'api/wallet/transactionDepositeDetails',
  Bank_Store: 'api/bank_account/store',
  Bank_Detail : 'api/bank_account/byId',
  Bank_Delete : 'api/bank_account/delete',
  PanVerification: 'api/PanVerification',
  Notification_List: 'notification/list',
  Notification_ById:'/notification/getNotificationById',
  Winning: 'api/winnings/byUserId',
  Wallet_Store: 'api/wallet_request/store',
  Wallet_Request: 'api/wallet_request/list',
  Final_Score: 'api/finalScore',
  Bonus_Data: 'api/bonusWallet/byUserId',
  EditProfile: 'api/editProfile',
  VerifyLogin:'api/verify-login',
  State:'api/state/list',
  EditImage: 'api/editImage',
  ShowTds:'api/wallet_request/showtTdsCalculation',
  Pan_Document:'api/documents/pan',
  Aadhar_Document:'api/documents/aadhar',
  Bank_Document:'api/documents/bank_account',
  Add_Expectation : 'api/userWinningExpectation/add',
  Edit_Expectation:'api/userWinningExpectation/edit/',
  Show_Expectation :'api/userWinningExpectation/',
  Range_Show : 'api/userWinningRange/',
  Show_Reason:'reason/list',
  HelpAndSupport:'api/helpAndSupport_request/store',
  SupportTitle:'supportTitle/list'
};
